### ISSUE TITLE
Not able to run attachment-downloader

### ISSUE THREAD

**Issue by atix1906** [jamesridgway/attachment-downloader#19]
Hello
I am trying to run the attachment downloader, but unfortunately it is not working for me, not sure what I am doing wrong...
Installation worked fine with pip and then I tried running it 
`import attachment_downloader 

attachment_downloader --host=imap.gmail.com --username=user --password='password' --output='C:\\test'`

It gives the following error:
**SyntaxError: can't assign to operator**

**Comment by jamesridgway** [comment]
A few quick questions:

1. Can you provide the full traceback error?
2. What python version are you using?
3. Whatr OS are you using?

**Comment by atix1906** [comment]
Hi @jamesridgway,
thank you for the quick response.
Regarding your questions:
1. `Traceback (most recent call last):
  File "C:\Users\atix\.platformio\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\atix\.platformio\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\atix\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\atix\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\atix\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\atix\.platformio\python3\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\atix\.platformio\python3\lib\runpy.py", line 236, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "c:\Users\atix\Documents\Programmieren\python\downloadEmailAttachments\downloadEmailAttachment.py", line 3
    attachment_downloader --host=imap.gmail.com --username=user --password='password' --output='C:\\test'    
    
    ^
SyntaxError: can't assign to operator`

2. Python 3.7.7
3. I am using Windows 10

**Comment by jamesridgway** [comment]
HI @atix1906 

So it looks like you're trying to create a file like this?

```
import attachment_downloader

attachment_downloader --host=imap.gmail.com --username=user --password='password' --output='C:\test
```

Attachment downloader is designed to be used as a command line application, it's not designed to be used as a library within a s cript.

So after you ran:

```
pip install attachment-downloader
```

You should be able to run something like this from your command line/terminal:

```
attachment-downloader --host imap.example.com --username mail@example.com --password pa55word \\
    --imap-folder invoices --output ~/Downloads
```

I am going to close this because this isn't an issue with attachment downloader.
