### ISSUE TITLE
ERROR - 'Struct' object has no attribute 'date'

### ISSUE THREAD

**Issue by hilocz** [jamesridgway/attachment-downloader#29]
I have latest version and getting on all messages above error. 

python-dateutil = 2.8.1-1.24

**Comment by jamesridgway** [comment]
Do the logs include anymore information? Can you send me the entire log output?

Thanks

**Comment by hilocz** [comment]
When using switch --date-after="2022-03-03T13:00:00" i'm getting this error

Traceback (most recent call last):
  File "attachment-downloader.py", line 88, in <module>
    (options, args) = parser.parse_args()
  File "/usr/lib64/python3.6/optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib64/python3.6/optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib64/python3.6/optparse.py", line 1501, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/lib64/python3.6/optparse.py", line 779, in process
    value = self.convert_value(opt, value)
  File "/usr/lib64/python3.6/optparse.py", line 771, in convert_value
    return self.check_value(opt, value)
  File "/usr/lib64/python3.6/optparse.py", line 766, in check_value
    return checker(self, opt, value)
  File "attachment-downloader.py", line 18, in valid_date
    parsed_value = datetime.datetime.fromisoformat(value)
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

**Comment by jamesridgway** [comment]
I think this should fix your issue:
https://github.com/jamesridgway/attachment-downloader/pull/31

I suspect you may be using Python 3.6 and this should fix the issue. I need to do a new release which I will do shortly.

**Comment by jamesridgway** [comment]
1.2.2 has now been released which should fix this issue
